title: Cinthia M. Souza
email: souza.cinthiamikaela@gmail.com
logo: /assets/img/46195145.jpeg
favicon: true
show_downloads: false
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
 
